name: 'travaux_angers'
version: '1.0.0'
config-version: 2

profile: 'travaux_angers'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  travaux_angers:
    # Configuration par défaut pour tous les modèles
    +materialized: view
    # Configuration spécifique par dossier
    analysis:
      +enabled: true
      +materialized: view
    bronze:
      +schema: bronze
      +materialized: view
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table
